BATCH_SIZE: 128
GAMMA: 0.999
EPS_START: 0.9
EPS_END: 0.05
EPS_DECAY: 5000
TARGET_UPDATE: 50
MEMORY_SIZE: 100000
END_SCORE: 200
TRAINING_STOP: 142
NUM_EPISODES: 30000
LAST_EPISODES_NUM: 20

HIDDEN_LAYER1: 16
HIDDEN_LAYER2: 32
HIDDEN_LAYER3: 32

USE_CUDA: True